/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package laptopdeployment;

import javax.swing.JOptionPane;

/**
 *
 * @author ndorelus
 */
public class CreateChecklist extends javax.swing.JFrame {

    /** Creates new form CreateChecklist */
    public CreateChecklist() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 87, 142));

        jTabbedPane1.setBackground(new java.awt.Color(89, 192, 213));

        jPanel2.setBackground(new java.awt.Color(0, 87, 142));

        jCheckBox2.setBackground(new java.awt.Color(0, 87, 142));
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Login as .\\blue and enter user's full name in description");

        jCheckBox3.setBackground(new java.awt.Color(0, 87, 142));
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Verify machine is on domain, rename using Model-Serial naming convention and restart");

        jCheckBox4.setBackground(new java.awt.Color(0, 87, 142));
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Log in with admin, turn on Bitlocker, backup key to \\\\root\\tech\\Blue Documentation\\BitlockerRecoveryKey\\");

            jCheckBox5.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox5.setText("Verify Proofpoint is installed");

            jCheckBox6.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox6.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox6.setText("Run Lenovo System Update/HP Support Assistant (whichever is applicable)");
            jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jCheckBox6ActionPerformed(evt);
                }
            });

            jCheckBox7.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox7.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox7.setText("Move machine to proper OU, verify Checkpoint is installed and up to date");

            jCheckBox8.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox8.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox8.setText("Run Windows Updates");

            jCheckBox25.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox25.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox25.setText("Add machine to user in Track-It!");

            jCheckBox26.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox26.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox26.setText("Update docking station firmware");

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox26)
                        .addComponent(jCheckBox25)
                        .addComponent(jCheckBox8)
                        .addComponent(jCheckBox7)
                        .addComponent(jCheckBox6)
                        .addComponent(jCheckBox5)
                        .addComponent(jCheckBox4)
                        .addComponent(jCheckBox3)
                        .addComponent(jCheckBox2))
                    .addGap(35, 35, 35))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(jCheckBox2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox25)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox26)
                    .addContainerGap(80, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Hardware Setup", jPanel2);

            jPanel3.setBackground(new java.awt.Color(0, 87, 142));

            jCheckBox9.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox9.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox9.setText("Login as user");

            jCheckBox10.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox10.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox10.setText("Launch Outlook and let emails fully sync");

            jCheckBox11.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox11.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox11.setText("Log the machine into Blue-N Wi-Fi");

            jCheckBox12.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox12.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox12.setText("Log into Cisco AnyConnect VPN and then disconnect");

            jCheckBox17.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox17.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox17.setText("Move Outlook Signature files to proper location");

            jCheckBox18.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox18.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox18.setText("Transfer Chrome bookmarks");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox18)
                        .addComponent(jCheckBox17)
                        .addComponent(jCheckBox12)
                        .addComponent(jCheckBox11)
                        .addComponent(jCheckBox10)
                        .addComponent(jCheckBox9))
                    .addContainerGap(385, Short.MAX_VALUE))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jCheckBox9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox11)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox12)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox17)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox18)
                    .addContainerGap(135, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("User Login Items", jPanel3);

            jPanel4.setBackground(new java.awt.Color(0, 87, 142));

            jCheckBox13.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox13.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox13.setText("Install local printers - WILTON ONLY");

            jCheckBox14.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox14.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox14.setText("Unpin Edge, Store,and Mail from taskbar");
            jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jCheckBox14ActionPerformed(evt);
                }
            });

            jCheckBox15.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox15.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox15.setText("Pin IE, Chrome, and Outlook to taskbar");

            jCheckBox16.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox16.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox16.setText("Set Default Apps: Chrome, Outook, Nuance PDF");

            jCheckBox19.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox19.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox19.setText("Restore default settings in Power Options and set Windows to do nothing when lid is closed");

            jCheckBox20.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox20.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox20.setText("In File Explorer options, change \"Open File Explorer\" to \"This PC\" and uncheck \"Show recently used files\"");

            jCheckBox22.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox22.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox22.setText("Right-click desktop > personalize > themes > desktop icon settings and select all boxes");

            jCheckBox23.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox23.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox23.setText("Verify that the time is correct and that Windows is set to the correct time zone");

            jCheckBox24.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox24.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox24.setText("In touchpad settings, set three-finger and four-finger gestures to do nothing");

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox24)
                        .addComponent(jCheckBox23)
                        .addComponent(jCheckBox22)
                        .addComponent(jCheckBox20)
                        .addComponent(jCheckBox19)
                        .addComponent(jCheckBox16)
                        .addComponent(jCheckBox15)
                        .addComponent(jCheckBox14)
                        .addComponent(jCheckBox13))
                    .addContainerGap(135, Short.MAX_VALUE))
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(jCheckBox13)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox14)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox15)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox16)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox19)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox20)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox22)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox23)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox24)
                    .addContainerGap(80, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Windows Settings", jPanel4);

            jPanel5.setBackground(new java.awt.Color(0, 87, 142));

            jCheckBox27.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox27.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox27.setText("Provide Welcome Sheet with computer");

            jCheckBox28.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox28.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox28.setText("Schedule an IT Onboarding meeting");

            jCheckBox29.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox29.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox29.setText("Set user account to force password change on next login");

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox29)
                        .addComponent(jCheckBox28)
                        .addComponent(jCheckBox27))
                    .addContainerGap(361, Short.MAX_VALUE))
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(jCheckBox27)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox28)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox29)
                    .addContainerGap(153, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Onboarding", jPanel5);
            if (!Toolkit.getCurrentUser().getIsNewHire()) jTabbedPane1.setEnabledAt(3, false);

            jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("Checklist for " + Toolkit.getCurrentUser().getFull() + "'s Current Computer");

            jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jButton1.setText("Create Checklist");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jButton2.setText("Cancel");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap())
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(296, 296, 296))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton2)
                    .addContainerGap(28, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        super.dispose();
        ViewUsers view = new ViewUsers();
        view.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Checklist check = new Checklist();
        
        // HARDWARE SETUP TAB //
        if (jCheckBox2.isSelected()) check.setBlueLogin(true);
        if (jCheckBox3.isSelected()) check.setNameComputer(true);
        if (jCheckBox4.isSelected()) check.setBitLocker(true);
        if (jCheckBox5.isSelected()) check.setProofpoint(true);
        if (jCheckBox6.isSelected()) check.setSystemUpdate(true);
        if (jCheckBox7.isSelected()) check.setMoveOU(true);
        if (jCheckBox8.isSelected()) check.setWindowsUpdate(true);
        if (jCheckBox25.isSelected()) check.setTrackIT(true);
        if (jCheckBox26.isSelected()) check.setDockingStation(true);
        
        // USER LOGIN ITEMS TAB //
        if (jCheckBox9.isSelected()) check.setUserLogin(true);
        if (jCheckBox10.isSelected()) check.setOutlook(true);
        if (jCheckBox11.isSelected()) check.setWifi(true);
        if (jCheckBox12.isSelected()) check.setVPN(true);
        if (jCheckBox17.isSelected()) check.setSignatures(true);
        if (jCheckBox18.isSelected()) check.setChromeBookmarks(true);
        
        // WINDOWS SETTINGS TAB //
        if (jCheckBox13.isSelected()) check.setPrinters(true);
        if (jCheckBox14.isSelected()) check.setUnpin(true);
        if (jCheckBox15.isSelected()) check.setPin(true);
        if (jCheckBox16.isSelected()) check.setDefaultApps(true);
        if (jCheckBox19.isSelected()) check.setDefaultPower(true);
        if (jCheckBox20.isSelected()) check.setFileExplorer(true);
        if (jCheckBox22.isSelected()) check.setDesktopIcons(true);
        if (jCheckBox23.isSelected()) check.setTimeZone(true);
        if (jCheckBox24.isSelected()) check.setTouchpad(true);
        
        // ONBOARDING TAB //
        if (jCheckBox27.isSelected()) check.setWelcomeSheet(true);
        if (jCheckBox28.isSelected()) check.setMeeting(true);
        if (jCheckBox29.isSelected()) check.setPasswordChange(true);
        
        Toolkit.getCurrentUser().getCurrentComputer().assignChecklist(check);
        
        JOptionPane.showMessageDialog(rootPane, "This checklist has successfully been assigned to " + Toolkit.getCurrentUser().getFull() + "'s computer '" + Toolkit.getCurrentUser().getCurrentComputer().getName() + "'.", "Checklist Successfully Assigned", JOptionPane.PLAIN_MESSAGE);
        super.dispose();
        ViewUsers view = new ViewUsers();
        view.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateChecklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateChecklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateChecklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateChecklist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateChecklist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
