/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laptopdeployment;

/**
 *
 * @author ndorelus
 */
public class ViewChecklists extends javax.swing.JFrame {

    /**
     * Creates new form ViewChecklists
     */
    public ViewChecklists() {
        initComponents();
    }
    
    User user = Toolkit.getCurrentUser();
    String[] names = user.getComputerNames();
    Checklist temp = user.getCurrentChecklist();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox56 = new javax.swing.JCheckBox();
        jCheckBox57 = new javax.swing.JCheckBox();
        jCheckBox58 = new javax.swing.JCheckBox();
        jCheckBox59 = new javax.swing.JCheckBox();
        jCheckBox60 = new javax.swing.JCheckBox();
        jCheckBox61 = new javax.swing.JCheckBox();
        jCheckBox62 = new javax.swing.JCheckBox();
        jCheckBox63 = new javax.swing.JCheckBox();
        jCheckBox64 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox65 = new javax.swing.JCheckBox();
        jCheckBox66 = new javax.swing.JCheckBox();
        jCheckBox67 = new javax.swing.JCheckBox();
        jCheckBox68 = new javax.swing.JCheckBox();
        jCheckBox69 = new javax.swing.JCheckBox();
        jCheckBox70 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox71 = new javax.swing.JCheckBox();
        jCheckBox72 = new javax.swing.JCheckBox();
        jCheckBox73 = new javax.swing.JCheckBox();
        jCheckBox74 = new javax.swing.JCheckBox();
        jCheckBox75 = new javax.swing.JCheckBox();
        jCheckBox76 = new javax.swing.JCheckBox();
        jCheckBox77 = new javax.swing.JCheckBox();
        jCheckBox78 = new javax.swing.JCheckBox();
        jCheckBox79 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox80 = new javax.swing.JCheckBox();
        jCheckBox81 = new javax.swing.JCheckBox();
        jCheckBox82 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 87, 142));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = names;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jTabbedPane1.setBackground(new java.awt.Color(89, 192, 213));

        jPanel1.setBackground(new java.awt.Color(0, 87, 142));

        jCheckBox56.setBackground(new java.awt.Color(0, 87, 142));
        jCheckBox56.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox56.setText("Login as .\\blue and enter user's full name in description");

        jCheckBox57.setBackground(new java.awt.Color(0, 87, 142));
        jCheckBox57.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox57.setText("Verify machine is on domain, rename using Model-Serial naming convention and restart");

        jCheckBox58.setBackground(new java.awt.Color(0, 87, 142));
        jCheckBox58.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox58.setText("Log in with admin, turn on Bitlocker, backup key to \\\\root\\tech\\Blue Documentation\\BitlockerRecoveryKey\\");

            jCheckBox59.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox59.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox59.setText("Verify Proofpoint is installed");

            jCheckBox60.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox60.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox60.setText("Run Lenovo System Update/HP Support Assistant (whichever is applicable)");
            jCheckBox60.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jCheckBox60ActionPerformed(evt);
                }
            });

            jCheckBox61.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox61.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox61.setText("Move machine to proper OU, verify Checkpoint is installed and up to date");

            jCheckBox62.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox62.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox62.setText("Run Windows Updates");

            jCheckBox63.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox63.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox63.setText("Add machine to user in Track-It!");

            jCheckBox64.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox64.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox64.setText("Update docking station firmware");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(34, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox64)
                        .addComponent(jCheckBox63)
                        .addComponent(jCheckBox62)
                        .addComponent(jCheckBox61)
                        .addComponent(jCheckBox60)
                        .addComponent(jCheckBox59)
                        .addComponent(jCheckBox58)
                        .addComponent(jCheckBox57)
                        .addComponent(jCheckBox56))
                    .addGap(28, 28, 28))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(55, Short.MAX_VALUE)
                    .addComponent(jCheckBox56)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox57)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox58)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox59)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox60)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox61)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox62)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox63)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox64)
                    .addGap(50, 50, 50))
            );

            jTabbedPane1.addTab("Hardware Setup", jPanel1);

            jPanel2.setBackground(new java.awt.Color(0, 87, 142));

            jCheckBox65.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox65.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox65.setText("Login as user");

            jCheckBox66.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox66.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox66.setText("Launch Outlook and let emails fully sync");

            jCheckBox67.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox67.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox67.setText("Log the machine into Blue-N Wi-Fi");

            jCheckBox68.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox68.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox68.setText("Log into Cisco AnyConnect VPN and then disconnect");

            jCheckBox69.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox69.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox69.setText("Move Outlook Signature files to proper location");

            jCheckBox70.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox70.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox70.setText("Transfer Chrome bookmarks");

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox70)
                        .addComponent(jCheckBox69)
                        .addComponent(jCheckBox68)
                        .addComponent(jCheckBox67)
                        .addComponent(jCheckBox66)
                        .addComponent(jCheckBox65))
                    .addContainerGap(286, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jCheckBox65)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox66)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox67)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox68)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox69)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox70)
                    .addContainerGap(89, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("User Login Items", jPanel2);

            jPanel3.setBackground(new java.awt.Color(0, 87, 142));

            jCheckBox71.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox71.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox71.setText("Install local printers - WILTON ONLY");

            jCheckBox72.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox72.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox72.setText("Unpin Edge, Store,and Mail from taskbar");
            jCheckBox72.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jCheckBox72ActionPerformed(evt);
                }
            });

            jCheckBox73.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox73.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox73.setText("Pin IE, Chrome, and Outlook to taskbar");

            jCheckBox74.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox74.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox74.setText("Set Default Apps: Chrome, Outook, Nuance PDF");

            jCheckBox75.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox75.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox75.setText("Restore default settings in Power Options and set Windows to do nothing when lid is closed");

            jCheckBox76.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox76.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox76.setText("In File Explorer options, change \"Open File Explorer\" to \"This PC\" and uncheck \"Show recently used files\"");

            jCheckBox77.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox77.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox77.setText("Right-click desktop > personalize > themes > desktop icon settings and select all boxes");

            jCheckBox78.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox78.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox78.setText("Verify that the time is correct and that Windows is set to the correct time zone");

            jCheckBox79.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox79.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox79.setText("In touchpad settings, set three-finger and four-finger gestures to do nothing");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox79)
                        .addComponent(jCheckBox78)
                        .addComponent(jCheckBox77)
                        .addComponent(jCheckBox76)
                        .addComponent(jCheckBox75)
                        .addComponent(jCheckBox74)
                        .addComponent(jCheckBox73)
                        .addComponent(jCheckBox72)
                        .addComponent(jCheckBox71))
                    .addGap(14, 14, 14))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jCheckBox71)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox72)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox73)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox74)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox75)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox76)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox77)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox78)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox79)
                    .addContainerGap(57, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Windows Settings", jPanel3);

            jPanel4.setBackground(new java.awt.Color(0, 87, 142));

            jCheckBox80.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox80.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox80.setText("Provide Welcome Sheet with computer");

            jCheckBox81.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox81.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox81.setText("Schedule an IT Onboarding meeting");

            jCheckBox82.setBackground(new java.awt.Color(0, 87, 142));
            jCheckBox82.setForeground(new java.awt.Color(255, 255, 255));
            jCheckBox82.setText("Set user account to force password change on next login");

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox82)
                        .addComponent(jCheckBox81)
                        .addComponent(jCheckBox80))
                    .addContainerGap(262, Short.MAX_VALUE))
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(jCheckBox80)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox81)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox82)
                    .addContainerGap(137, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Onboarding", jPanel4);

            jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jButton1.setText("Close Window");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(363, 363, 363)
                            .addComponent(jButton1)))
                    .addContainerGap(20, Short.MAX_VALUE))
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(159, 159, 159)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(63, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)
                    .addComponent(jButton1)
                    .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        refreshPage();
    }//GEN-LAST:event_jList1ValueChanged

    private void jCheckBox60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox60ActionPerformed

    private void jCheckBox72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox72ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        super.dispose();
        ViewUsers view = new ViewUsers();
        view.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewChecklists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewChecklists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewChecklists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewChecklists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewChecklists().setVisible(true);
            }
        });
    }
    
    /**
     * 
     * Changes the selection status of all the checkboxes to match the checklist of the currently selected computer
     */
    private void refreshPage() {
        Computer comp = user.getComputer(jList1.getSelectedIndex());
        if (comp.hasChecklist()) {
            temp = comp.getChecklist();
            // set all of the checkboxes to react to jList1's selection being changed
            
            enableAll();

            // HARDWARE SETUP TAB //
            jCheckBox56.setSelected(temp.getBlueLogin());
            jCheckBox57.setSelected(temp.getNameComputer());
            jCheckBox58.setSelected(temp.getBitLocker());
            jCheckBox59.setSelected(temp.getProofpoint());
            jCheckBox60.setSelected(temp.getSystemUpdate());
            jCheckBox61.setSelected(temp.getMoveOU());
            jCheckBox62.setSelected(temp.getWindowsUpdate());
            jCheckBox63.setSelected(temp.getTrackIT());
            jCheckBox64.setSelected(temp.getDockingStation());

            // USER LOGIN ITEMS TAB //
            jCheckBox65.setSelected(temp.getUserLogin());
            jCheckBox66.setSelected(temp.getOutlook());
            jCheckBox67.setSelected(temp.getWifi());
            jCheckBox68.setSelected(temp.getVPN());
            jCheckBox69.setSelected(temp.getSignatures());
            jCheckBox70.setSelected(temp.getChromeBookmarks());

            // WINDOWS SETTINGS TAB //
            jCheckBox71.setSelected(temp.getPrinters());
            jCheckBox72.setSelected(temp.getUnpin());
            jCheckBox73.setSelected(temp.getPin());
            jCheckBox74.setSelected(temp.getDefaultApps());
            jCheckBox75.setSelected(temp.getDefaultPower());
            jCheckBox76.setSelected(temp.getFileExplorer());
            jCheckBox77.setSelected(temp.getDesktopIcons());
            jCheckBox78.setSelected(temp.getTimeZone());
            jCheckBox79.setSelected(temp.getTouchpad());

            // ONBOARDING TAB //
            jCheckBox80.setSelected(temp.getWelcomeSheet());
            jCheckBox81.setSelected(temp.getMeeting());
            jCheckBox82.setSelected(temp.getPasswordChange());
        }
        else disableAll();
    }
    
    private void disableAll() {
        // HARDWARE SETUP TAB //
        jCheckBox56.setEnabled(false);
        jCheckBox57.setEnabled(false);
        jCheckBox58.setEnabled(false);
        jCheckBox59.setEnabled(false);
        jCheckBox60.setEnabled(false);
        jCheckBox61.setEnabled(false);
        jCheckBox62.setEnabled(false);
        jCheckBox63.setEnabled(false);
        jCheckBox64.setEnabled(false);
        
        // USER LOGIN ITEMS TAB //
        jCheckBox65.setEnabled(false);
        jCheckBox66.setEnabled(false);
        jCheckBox67.setEnabled(false);
        jCheckBox68.setEnabled(false);
        jCheckBox69.setEnabled(false);
        jCheckBox70.setEnabled(false);
        
        // WINDOWS SETTINGS TAB //
        jCheckBox71.setEnabled(false);
        jCheckBox72.setEnabled(false);
        jCheckBox73.setEnabled(false);
        jCheckBox74.setEnabled(false);
        jCheckBox75.setEnabled(false);
        jCheckBox76.setEnabled(false);
        jCheckBox77.setEnabled(false);
        jCheckBox78.setEnabled(false);
        jCheckBox79.setEnabled(false);
        
        // ONBOARDING TAB //
        jCheckBox80.setEnabled(false);
        jCheckBox81.setEnabled(false);
        jCheckBox82.setEnabled(false);
    }
    
    private void enableAll() {
        // HARDWARE SETUP TAB //
        jCheckBox56.setEnabled(true);
        jCheckBox57.setEnabled(true);
        jCheckBox58.setEnabled(true);
        jCheckBox59.setEnabled(true);
        jCheckBox60.setEnabled(true);
        jCheckBox61.setEnabled(true);
        jCheckBox62.setEnabled(true);
        jCheckBox63.setEnabled(true);
        jCheckBox64.setEnabled(true);
        
        // USER LOGIN ITEMS TAB //
        jCheckBox65.setEnabled(true);
        jCheckBox66.setEnabled(true);
        jCheckBox67.setEnabled(true);
        jCheckBox68.setEnabled(true);
        jCheckBox69.setEnabled(true);
        jCheckBox70.setEnabled(true);
        
        // WINDOWS SETTINGS TAB //
        jCheckBox71.setEnabled(true);
        jCheckBox72.setEnabled(true);
        jCheckBox73.setEnabled(true);
        jCheckBox74.setEnabled(true);
        jCheckBox75.setEnabled(true);
        jCheckBox76.setEnabled(true);
        jCheckBox77.setEnabled(true);
        jCheckBox78.setEnabled(true);
        jCheckBox79.setEnabled(true);
        
        // ONBOARDING TAB //
        jCheckBox80.setEnabled(true);
        jCheckBox81.setEnabled(true);
        jCheckBox82.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox56;
    private javax.swing.JCheckBox jCheckBox57;
    private javax.swing.JCheckBox jCheckBox58;
    private javax.swing.JCheckBox jCheckBox59;
    private javax.swing.JCheckBox jCheckBox60;
    private javax.swing.JCheckBox jCheckBox61;
    private javax.swing.JCheckBox jCheckBox62;
    private javax.swing.JCheckBox jCheckBox63;
    private javax.swing.JCheckBox jCheckBox64;
    private javax.swing.JCheckBox jCheckBox65;
    private javax.swing.JCheckBox jCheckBox66;
    private javax.swing.JCheckBox jCheckBox67;
    private javax.swing.JCheckBox jCheckBox68;
    private javax.swing.JCheckBox jCheckBox69;
    private javax.swing.JCheckBox jCheckBox70;
    private javax.swing.JCheckBox jCheckBox71;
    private javax.swing.JCheckBox jCheckBox72;
    private javax.swing.JCheckBox jCheckBox73;
    private javax.swing.JCheckBox jCheckBox74;
    private javax.swing.JCheckBox jCheckBox75;
    private javax.swing.JCheckBox jCheckBox76;
    private javax.swing.JCheckBox jCheckBox77;
    private javax.swing.JCheckBox jCheckBox78;
    private javax.swing.JCheckBox jCheckBox79;
    private javax.swing.JCheckBox jCheckBox80;
    private javax.swing.JCheckBox jCheckBox81;
    private javax.swing.JCheckBox jCheckBox82;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
